#!/usr/bin/env python3

import hal
import time

class HControl:
    def __init__(self, name):
        self.comp = hal.component(name)
        self.homed_state = False
        self.top_of_plate = None
        self.offset = 0
        self.bit_in = [
            'homing', 'home-sw', 'probing',
            'probe-sw', 'piercing', 'arc-ok',
            'pierce-and-cut',
            ]
        self.float_in = [
            'max-lim', 'min-lim', 'max-vel', 
            'homing-vel', 'pos-fb', 'home-offset',
            'probe-vel', 'pierce-hght', 'jump-hght',
            'pierce-delay', 'cut-hght',
            ]
        self.bit_out = [
            'homed', 'plasma-on',
            ]
        self.float_out = [
            'vel-cmd', 'offset', 
            ]
        self.pins_init()
        
    def pins_init(self):
        for i in self.bit_in:
            self.comp.newpin(i, hal.HAL_BIT, hal.HAL_IN)
        
        for i in self.float_in:
            self.comp.newpin(i, hal.HAL_FLOAT, hal.HAL_IN)
        
        for i in self.bit_out:
            self.comp.newpin(i, hal.HAL_BIT, hal.HAL_OUT)
        
        for i in self.float_out:
            self.comp.newpin(i, hal.HAL_FLOAT, hal.HAL_OUT)
        
    def ready(self):
        self.comp.ready()
        
    def homing(self):
        if self.homed_state:
            self.homed_state = False
            self.comp['homed'] = False
        else:
            while not self.comp['home-sw']:
                self.comp['vel-cmd'] = 10
            self.comp['vel-cmd'] = 0
            while self.comp['home-sw']:
                self.comp['vel-cmd'] = -10
            self.offset = self.comp['pos-fb']
            homed_zero = self.offset - self.comp['home-offset']
            while self.comp['pos-fb'] > homed_zero:
                self.comp['vel-cmd'] = -10
            self.comp['vel-cmd'] = 0
            self.homed_state = True
            self.comp['homed'] = True
            self.comp['offset'] = self.offset
            
    def probing(self):
        while not self.comp['probe-sw']:
            self.comp['vel-cmd'] = -20
        while self.comp['probe-sw']:
            self.comp['vel-cmd'] = 20
        self.comp['vel-cmd'] = 0
        self.top_of_plate = self.comp['pos-fb']
        
        
    def piercing(self):
        pierce_hght = self.top_of_plate + self.comp['pierce-hght']
        while pierce_hght > self.comp['pos-fb']:
            self.comp['vel-cmd'] = 20
        self.comp['vel-cmd'] = 0
        self.comp['plasma-on'] = True
        while not self.comp['arc-ok']:
            self.comp['vel-cmd'] = 0
        pierce_hght += self.comp['jump-hght']
        while pierce_hght > self.comp['pos-fb']:
            self.comp['vel-cmd'] = 20
        self.comp['vel-cmd'] = 0
        time.sleep(self.comp['pierce-delay'])
        pierce_hght = self.top_of_plate + self.comp['cut-hght']
        while pierce_hght < self.comp['pos-fb']:
            self.comp['vel-cmd'] = 20
        self.comp['vel-cmd'] = 0
        
    def pierce_and_cut(self):
        self.probing()
        self.piercing()
        
        
        
        
if __name__ == '__main__':
    hc = HControl('hcontrol')
    hc.ready()
    
try:
    while 1:
        if hc.comp['homing']:
            hc.homing()
        elif hc.comp['probing']:
            hc.probing()
        elif hc.comp['piercing']:
            hc.piercing()
        elif hc.comp['pierce-and-cut']:
            hc.pierce_and_cut()
        
        
except KeyboardInterrupt as e:
    print(e)